name = "reference-verifier"
main = "src/index.js"
compatibility_date = "2024-01-01"

[env.production]
vars = { 
  USE_PROXY = "false",
  GEMINI_MODEL_NAME = "gemini-2.5-flash-lite-preview-06-17"
}

# These will be set in Cloudflare dashboard as secrets
# [env.production.secrets]
# GEMINI_API_KEY
# GOOGLE_SEARCH_API_KEY
# GOOGLE_CSE_ID